name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.22'

    - name: Install dependencies (Linux & macOS)
      if: runner.os != 'Windows'
      run: |
        sudo apt-get update || true
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build
